name: workflow build and test

on: 
  push:
  schedule:
    - cron: '0 * * * *'

jobs:

  #usando a action pré-existente "Test Reporter" do GitHub 
  build-test:
    name: build and test
    runs-on: ubuntu-latest
    
    steps:
      # checkout the repo
      - uses: actions/checkout@v4

      # install packages
      - run: npm ci

       # run tests (configured to use jest-junit reporter)
      - run: npm test                 

      - name: Test Report
        uses: dorny/test-reporter@v2

        # run this step even if previous step failed
        if: success() || failure()   

        with:
          
          # Name of the check run which will be created
          name: JEST Tests      
          
          # Path to test results      
          path: reports/jest-*.xml  
          
          # Format of test results  
          reporter: jest-junit        
      
      # usando script próprio
      - run: echo "Testando e preparando relatório final de testes"
    